### ISSUE TITLE
Fix slather integration

### ISSUE THREAD

**Issue by towerz** [clappr/clappr-ios#41]

**Comment by barbosa** [comment]
It seems like since Xcode 7 was released (together with its new code coverage feature), slather scripts are conflicting with it. See https://github.com/venmo/slather/pull/99 and https://github.com/venmo/slather/pull/92. These PR's are intended to fix it, but they weren't merged yet.

By now, I think that the best thing to do is just disable slather's integration and follow the discussion here: https://github.com/venmo/slather/pull/99

I'm creating a PR to remove it and fix our travis build as well (#40).
